// stitches.config.ts
import { createStitches } from '@stitches/react';
import { Theme } from './design/theme';

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      ...Theme.colors,
    },
    radii: {
      ...Theme.radii,
    },
    space: {
      spacing0: Theme.measures.dimensionSpacing0.css,
      spacing025: Theme.measures.dimensionSpacing025.css,
      spacing050: Theme.measures.dimensionSpacing050.css,
      spacing100: Theme.measures.dimensionSpacing100.css,
      spacing150: Theme.measures.dimensionSpacing150.css,
      spacing200: Theme.measures.dimensionSpacing200.css,
      spacing300: Theme.measures.dimensionSpacing300.css,
      spacing400: Theme.measures.dimensionSpacing400.css,
      spacing500: Theme.measures.dimensionSpacing500.css,
      spacing600: Theme.measures.dimensionSpacing600.css,
      spacing800: Theme.measures.dimensionSpacing800.css,
      spacing1000: Theme.measures.dimensionSpacing1000.css,
      spacing1200: Theme.measures.dimensionSpacing1200.css,
      spacing1600: Theme.measures.dimensionSpacing1600.css,
      spacing2000: Theme.measures.dimensionSpacing2000.css,
      spacing2400: Theme.measures.dimensionSpacing2400.css,
      spacing3200: Theme.measures.dimensionSpacing3200.css,
    },
    fonts: {
      jumbo: Theme.typographies.headingJumbo.fontFamily,
      heading: Theme.typographies.headingH1.fontFamily,
      body: Theme.typographies.body.fontFamily,
      label: Theme.typographies.label.fontFamily,
      helperText: Theme.typographies.helperText.fontFamily,
    },
    fontSizes: {
      jumbo: Theme.typographies.headingJumbo.fontSize.css,
      h1: Theme.typographies.headingH1.fontSize.css,
      h2: Theme.typographies.headingH2.fontSize.css,
      h3: Theme.typographies.headingH3.fontSize.css,
      h4: Theme.typographies.headingH4.fontSize.css,
      h5: Theme.typographies.headingH5.fontSize.css,
      h6: Theme.typographies.headingH6.fontSize.css,
      body: Theme.typographies.body.fontSize.css,
      label: Theme.typographies.label.fontSize.css,
      helperText: Theme.typographies.helperText.fontSize.css,
    },
    lineHeights: {
      jumbo: Theme.typographies.headingJumbo.lineHeight.css,
      h1: Theme.typographies.headingH1.lineHeight.css,
      h2: Theme.typographies.headingH2.lineHeight.css,
      h3: Theme.typographies.headingH3.lineHeight.css,
      h4: Theme.typographies.headingH4.lineHeight.css,
      h5: Theme.typographies.headingH5.lineHeight.css,
      h6: Theme.typographies.headingH6.lineHeight.css,
      body: Theme.typographies.body.lineHeight.css,
      label: Theme.typographies.label.lineHeight.css,
      helperText: Theme.typographies.helperText.lineHeight.css,
    },
    letterSpacings: {
      jumbo: Theme.typographies.headingJumbo.letterSpacing.css,
      h1: Theme.typographies.headingH1.letterSpacing.css,
      h2: Theme.typographies.headingH2.letterSpacing.css,
      h3: Theme.typographies.headingH3.letterSpacing.css,
      h4: Theme.typographies.headingH4.letterSpacing.css,
      h5: Theme.typographies.headingH5.letterSpacing.css,
      h6: Theme.typographies.headingH6.letterSpacing.css,
      body: Theme.typographies.body.letterSpacing.css,
      label: Theme.typographies.label.letterSpacing.css,
      helperText: Theme.typographies.helperText.letterSpacing.css,
    },
    fontWeights: {
      jumbo: Theme.typographies.headingJumbo.fontWeight,
      h1: Theme.typographies.headingH1.fontWeight,
      h2: Theme.typographies.headingH2.fontWeight,
      h3: Theme.typographies.headingH3.fontWeight,
      h4: Theme.typographies.headingH4.fontWeight,
      h5: Theme.typographies.headingH5.fontWeight,
      h6: Theme.typographies.headingH6.fontWeight,
      body: Theme.typographies.body.fontWeight,
      label: Theme.typographies.label.fontWeight,
      helperText: Theme.typographies.helperText.fontWeight,
    }
  },
  media: {
    xs: `(min-width: ${Theme.measures.dimensionBreakpointXs.css})`,
    sm: `(min-width: ${Theme.measures.dimensionBreakpointSm.css})`,
    md: `(min-width: ${Theme.measures.dimensionBreakpointMd.css})`,
    lg: `(min-width: ${Theme.measures.dimensionBreakpointLg.css})`,
    xl: `(min-width: ${Theme.measures.dimensionBreakpointXl.css})`,
  },
});